server:
  port: 8080

spring:
  datasource:
    hikari:
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/dblcmp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zhp.lcmp.dao

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true