server:
  port: 8089

#jdbc:p6spy:mysql://127.0.0.1:3306/dblcmp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
#
#spring:
#  datasource:
#    url:  jdbc:p6spy:mysql://127.0.0.1:3306/dblcmp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    username: root
#    password: root
#    hikari:
#      connection-timeout: 30000
#      max-lifetime: 1800000
#      idle-timeout: 600000
#      maximum-pool-size: 15
#      minimum-idle: 10
#      connection-test-query: SELECT 1 FROM DUAL

mybatis:
  mapper-locations: classpath:mapper/*.xml
